INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Igor Casa Grande', '2018-12-26');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Paulo Cavalcanti', '1957-08-01');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Erick Aragão', '2007-10-17');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Kaique Abreu', '1987-09-08');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Isaque Peixoto', '1965-10-05');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Dr. Mateus da Paz', '2007-05-28');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Gabriel Leão', '2011-01-04');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Stephany Fernandes', '2019-05-16');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Gustavo Melo', '1921-08-21');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Benjamin Ribeiro', '2003-03-08');

INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('rerum', '1998-06-25', 7);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('veniam', '2009-05-17', 8);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('temporibus', '1981-07-13', 8);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('qui', '1981-08-05', 2);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('odio', '1971-08-05', 1);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('delectus', '1975-04-03', 4);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('beatae', '2019-07-24', 5);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('quod', '2011-09-06', 6);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('expedita', '1977-04-24', 3);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('nostrum', '1977-10-26', 3);

INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Dra. Lívia Aparecida', 'qcardoso@example.net', '2012-08-31');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Fernanda Azevedo', 'matheuscorreia@example.org', '1991-10-22');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Bruna Barbosa', 'lorenacamargo@example.net', '1970-11-24');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Luna Guerra', 'pfogaca@example.org', '2007-01-04');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Levi Mendonça', 'ana-claracamara@example.com', '2020-08-06');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Luna Cavalcante', 'das-neveskamilly@example.com', '1976-06-09');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Valentim Pires', 'piresstephany@example.net', '2002-10-05');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Dra. Maria Liz Almeida', 'gael-henrique07@example.net', '2022-11-14');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Jade Vasconcelos', 'rochamaria-luisa@example.com', '1971-01-13');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Davi Lucca Almeida', 'theomendonca@example.com', '1973-11-04');

INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('atque', '5:10', 3);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('molestiae', '4:58', 10);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('eius', '5:49', 10);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('vel', '4:47', 2);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('quis', '2:22', 1);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('ut', '2:47', 10);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('voluptatum', '3:08', 3);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('ullam', '2:45', 3);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('perferendis', '3:18', 7);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('deserunt', '3:04', 3);

INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('veniam', 1);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('cum', 6);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('exercitationem', 10);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('nesciunt', 7);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('magnam', 5);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('laboriosam', 5);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('quibusdam', 8);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('velit', 9);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('vel', 1);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('libero', 5);

INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (2, 2);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (9, 10);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (10, 7);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (10, 5);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (4, 7);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (10, 9);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (6, 2);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (2, 6);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (6, 8);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (1, 6);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (6, 8);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (4, 8);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (6, 1);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (2, 6);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (1, 6);

INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (4, 5);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (5, 4);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (3, 5);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (7, 4);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (2, 1);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (6, 3);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (6, 3);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (10, 3);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (5, 4);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (2, 1);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (7, 6);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (7, 3);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (9, 6);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (8, 10);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (10, 2);
