use project_spotify;

INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Ana Julia Sampaio', '1990-06-19');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Nicolas Ribeiro', '1946-02-09');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Sra. Valentina Porto', '2015-08-19');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Sarah Melo', '1993-04-24');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Sra. Ana Laura Leão', '1943-03-10');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Carlos Eduardo Câmara', '1959-10-28');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Benicio da Luz', '2011-01-16');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Pietra Jesus', '1997-08-11');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Dante Cardoso', '2024-05-11');
INSERT INTO ARTISTA (Nome, Data_Nascimento) VALUES ('Luna Melo', '1960-01-22');

INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('assumenda', '1980-10-18', 5);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('voluptatibus', '1996-08-29', 2);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('exercitationem', '1974-01-22', 6);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('omnis', '2023-10-20', 5);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('eum', '2019-08-11', 4);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('aspernatur', '2020-11-17', 1);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('cum', '2023-09-19', 10);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('deleniti', '1970-11-26', 5);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('quis', '1996-08-02', 9);
INSERT INTO DISCO (Titulo, Data_Lancamento, ID_Artista) VALUES ('veniam', '1972-11-05', 3);

INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Sophia Almeida', 'costelamaria@example.com', '2018-07-26');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Luan Silva', 'benjamin06@example.net', '1986-11-01');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Elisa das Neves', 'eloah79@example.net', '1978-09-08');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Nina Vargas', 'britoisabelly@example.org', '2015-09-19');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Marcelo Camargo', 'vitor-gabrielfreitas@example.net', '2015-12-13');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Oliver Nascimento', 'ana-lauracamargo@example.net', '1982-10-31');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Murilo Freitas', 'enrico95@example.net', '1974-11-08');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Guilherme Lima', 'oda-cunha@example.org', '2000-08-01');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Manuela Duarte', 'jose42@example.org', '2003-04-28');
INSERT INTO USUARIO (Nome, Email, Data_Registro) VALUES ('Aylla Aragão', 'cunhalara@example.org', '1985-03-26');

INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('nobis', '2:17', 6);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('enim', '5:51', 3);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('in', '5:18', 1);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('aliquam', '4:56', 2);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('hic', '2:48', 9);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('minima', '2:52', 10);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('labore', '2:21', 1);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('illum', '5:31', 2);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('reiciendis', '5:40', 8);
INSERT INTO MUSICA (Titulo, Duracao, ID_Disco) VALUES ('aperiam', '3:44', 5);

INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('illo', 7);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('rerum', 9);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('perferendis', 6);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('totam', 1);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('ratione', 9);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('fugit', 7);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('quidem', 9);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('nisi', 4);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('dolores', 10);
INSERT INTO PLAYLIST (Titulo, ID_Usuario) VALUES ('dicta', 9);

INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (10, 3);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (8, 10);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (1, 2);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (10, 9);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (2, 6);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (2, 3);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (8, 6);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (2, 3);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (9, 3);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (1, 5);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (6, 4);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (4, 4);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (3, 10);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (6, 10);
INSERT INTO MUSICA_PLAYLIST (ID_Musica, ID_Playlist) VALUES (4, 10);

INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (8, 8);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (7, 6);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (3, 8);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (5, 4);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (4, 2);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (4, 10);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (5, 1);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (7, 9);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (10, 8);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (4, 4);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (10, 1);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (2, 6);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (10, 2);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (2, 2);
INSERT INTO MUSICA_ARTISTA (ID_Musica, ID_Artista) VALUES (7, 4);
